# Generated by Django 4.1.6 on 2023-02-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='hangrymealsapi.recipe')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='hangrymealsapi.recipe')),
                ('saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='hangrymealsapi.recipe')),
                ('sunday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='hangrymealsapi.recipe')),
                ('thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='hangrymealsapi.recipe')),
                ('tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='hangrymealsapi.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.user')),
                ('wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='hangrymealsapi.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.user'),
        ),
        migrations.CreateModel(
            name='PantryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.ingredient')),
                ('pantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.pantry')),
            ],
        ),
        migrations.AddField(
            model_name='pantry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.user'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangrymealsapi.user'),
        ),
    ]
